version: 0.0
os: linux

# source will only contain your project's files.
files:
  - source: /
    destination: /home/ubuntu
file_exists_behavior: OVERWRITE
# This last point isn't needed since Blue/Green brings up new instances, but maybe
# some installation script like ./install could get in the way.

# To learn more about hooks, visit the docs here:
# https://docs.aws.amazon.com/codedeploy/latest/userguide/reference-appspec-file-structure-hooks.html#appspec-hooks-server
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
