#!/bin/bash

cd /home/ubuntu

# This is Django specific. This is where you'll need to replace
# things if you're not using Django 
# source django_app/myvenv/bin/activate
export DJANGO_SETTINGS_MODULE="django_app.settings"

# The following is Django oriented where I'm starting my HTTP server. If you're using a
# different web framework, understand that my port is on 8000 so that NGINX, the reverse
# proxy, can handle all the requests.
# How many workers? https://docs.gunicorn.org/en/stable/design.html#how-many-workers
gunicorn --bind 0.0.0.0:8000  --chdir /home/ubuntu/django_app django_app.wsgi:application
